name: BAT
channels:
  - defaults
  - default
dependencies:
  - python
  - scipy
  - matplotlib
  - pip
  - pandas
  - numpy
  - natsort
  - pyopengl
  - pyqt
  - ipykernel
  - pip:
      - hydra-core
      - omegaconf
      - pyqtgraph
      - pyroomacoustics
      - sounddevice
      - soundfile
      - keyboard
