blocksize: 1024
fs: 192000
channels: 8
default_file: "single_bat_1234.wav"
default_layout: "single_bat_1234.csv"
default_device: null

# Source detection parameters
vsound: 340
threshold: 1e-4

# Butterworth highpass filter parameters
filter_order: 1
cutoff_freq: 10000